services:
  nvslam:
    tty: true
    stdin_open: true
    working_dir: /cuvslam
    runtime: nvidia
    privileged: true
    network_mode: host
    build:
      context: .
      dockerfile: docker/Dockerfile.realsense-cu13
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1
      - _X11_NO_MITSHM=1
      - _MITSHM=0
    volumes:
      - .:/cuvslam
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ${DATASETS:-${HOME}/.datasets}:${DATASETS:-${HOME}/datasets}
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bus/usb
